### ISSUE TITLE
Замечания к форуму, редактору на боевом

### ISSUE THREAD

**Issue by milana-tulius** [kozzztik/tulius#119]
1. в редакторе в набираемом тексте на телефоне выделяется только одно слово.
2. ReferenceError: comments is not defined
сообщение выскочило, когда произвела следующие действия:
Написала новый пост. Появилась сбоку панель новых сообщений с 1 непрочитанным сообщением - моим. Но самого сообщения не увидела. Вышла в список тем.
Появилось данное сообщение об ошибке.
В списке тем горит лампочка о моем непрочитанном сообщении.
Снова по лампочке вошла в тему. 
3. В другой раз при описанном выше действии проявился еще один баг. В теме до сих пор висит  1 непрочитанное сообщение и горит лампочка в списке тем, хотя я несколько раз заходила в тему и выходила.

**Comment by kozzztik** [comment]
По пункту 3 - лампочка теперь не гаснет от входа и выхода в тему. Нужно "прочитать" непрочитанное сообщение, задержать на нем мышку на секунду.
