### ISSUE TITLE
Баги версии 27.08.20 - 1

### ISSUE THREAD

**Issue by milana-tulius** [kozzztik/tulius#200]
Игровой форум.
1. Рядовым пользователем не отправляются сообщения в общей и приватной теме. Error: Request failed with status code 403  Например:
пользователь Comandor, Tulius   http://test.tulius.co-de.org/play/746/room/49723   во всех темах
2. Рядовой пользователь, прилинкованный к двум персонажам, видит в комнате только одну приватную тему для одного из его персонажей. См. http://test.tulius.co-de.org/play/746/room/49744 Пользователь Comandor
3. Не видно присутствующих на форуме в списке присутствующих 
4. В форме отправке сообщения нет поля выбора персонажа, от которого пишется сообщение, если есть возможность писать от разных персонажей.
5. Для ведущего - админа: просьба - пусть по умолчанию сообщение отправляется от персонажа, к которому админ прилинкован. Сейчас оно отправляется от нулевого пользователя.
Главный форум.
Та же проблема, что выше в п. 1. Писать может только админ соответствующих комнат.

**Comment by kozzztik** [comment]
Исправлены пункты 1 и 4, пункт 2 работает, просто второму привату не выданы права пользователя.

**Comment by kozzztik** [comment]
Пункты 3 и 5 исправлены с #206

**Comment by kozzztik** [comment]
последнее предложение исправлено с #207
