### ISSUE TITLE
Авторизация через ВК дает неожиданный результат

### ISSUE THREAD

**Issue by milana-tulius** [kozzztik/tulius#24]
При авторизации через ВК вход осуществляется со своего аккаунта ан Тулиусе. (Баг или фича?) Заходила с ГуглХрома, Яндекс-браузера и Оперы. На Опере предварительно авторизовалась не своим, а фейковым аккаунтом на ВК - на Тулиусе все равно авторизуюсь под аккаунтом admin. 
Пока не могу проверить иные варианты.

**Comment by kozzztik** [comment]
Проверьте не совпадают ли почтовые ящики. Сопоставление учеток вконтакте и Тулиуса происходит по почтовому ящику. Если ваши фейковые учетки привязаны к тому же почтовому ящику что и admin учтека, то все они туда будут под нее авторизовывать.
Сейчас проверил, меня корректно авторизует. Единственное, новую учетку не создает, это надо поправить.

**Comment by milana-tulius** [comment]
Я проверяла. admin (на Тулиусе) и мой аккаунт на ВК привязаны к одному ящику. Однако фейковый аккаунт ВК непривязан ни к какой почте, и открывала я его в отдельном браузере, где я не авторизовалась прежде ни в ВК, ни на Тулиусе.
Буду разбираться.

**Comment by kozzztik** [comment]
Поправил создание новых учеток, проверяйте.
