### ISSUE TITLE
Админка игры. Исключение на странице создания формы заявки.

### ISSUE THREAD

**Issue by milana-tulius** [kozzztik/tulius#31]
http://test.tulius.com/games/edit_game/445/requests/
Страница не открывается.

**Comment by kozzztik** [comment]
Видимо починил вместе с остальными. Проверяйте.

**Comment by milana-tulius** [comment]
http://test.tulius.com/games/edit_game/445/request_form/
На самом деле речь шла об этой странице.
Создание форм заявок

**Comment by kozzztik** [comment]
промахнулся в комментарии к коммиту, закрыта не эта задача.
