### ISSUE TITLE
Не удается написать комментарий на форуме сайта.

### ISSUE THREAD

**Issue by milana-tulius** [kozzztik/tulius#33]
При попытке прокомментировать - сообщение Internal Server Error

 Тоже самое из расширенной формы ответа.Вне зависимости от настроек доступа, новую тему создать не получается: при клике на кнопку “создать” ничего не происходит.

**Comment by milana-tulius** [comment]
Также не создаются новые темы.

**Comment by kozzztik** [comment]
Добавление комментариев поправил, с кнопкой пока не понятно.

**Comment by milana-tulius** [comment]
Тема просто не создается.

**Comment by kozzztik** [comment]
Да, я в курсе. Пока не понял почему.

**Comment by kozzztik** [comment]
Fixed with #67
