### ISSUE TITLE
Игроки. Проблема с сортировкой.

### ISSUE THREAD

**Issue by milana-tulius** [kozzztik/tulius#37]
При вторичной сортировке не работает фильтр по активным игрокам, отображаются все, даже отключенные боты.

"Пункт меню "игроки" - открывается, как и на нынешней версии, в режиме сортировки по убыванию написанных сюжетов, но только первая страница - уже на второй что на действующей версии, что на тестовой все сбито и не о том. На тестовой - фильтр игроков по количеству сыгранных игр выдал кучу каких-то левых имен, у которых значится одна сыгранная игра.. но этот фильтр работает до конца, т.е в конце все-таки реальные игроки с реально возрастающим количеством сыгранных игр. 
А вот возвращение фильтра на сортировку по количеству сюжетов дало вообще левую сортировку безо всякой привязки к количеству сюжетов",
- пишет Таня. Проверила, так и есть.

Сортировка игроков работает один раз, При попытке пересортировать по-другому правильного порядка не получается.

**Comment by kozzztik** [comment]
Обратите внимание, по количеству игр там две сортировки - по убыванию и возрастанию. По возрастанию всегда будут первыми люди с минимальным количеством игр.
А вот сортировку по сюжетам - поправил, проверяйте.

**Comment by milana-tulius** [comment]
А нельзя ли совсем исключить из списка пользователей неактивных пользователей, как при сортировке по количеству игр.
" не работает фильтр по активным игрокам, отображаются все, даже отключенные боты" - при сортировке по сюжетам, алфавиту и дате регистрации.

**Comment by kozzztik** [comment]
Деактивированные боты там всегда были исключены для всех выборок.

**Comment by milana-tulius** [comment]
Тем не менее они отображаются в списке игроков. 225 страниц пользователей - это вместе с ними.
