### ISSUE TITLE
Исключения на игровом форуме.

### ISSUE THREAD

**Issue by milana-tulius** [kozzztik/tulius#41]
Темы и посты в игре открываются через раз.
Стачала тестировала переход по ссылке к последнему сообщению.
Это, н-р, открывается: http://test.tulius.com/play/thread/42146/?page=2#2228242
А это, н-р, - нет: http://test.tulius.com/play/thread/42112/?page=2#2228490
Непонятно.
То же с переходами к по ссылкам темам: 
Да - http://test.tulius.com/play/thread/42163/
Нет - http://test.tulius.com/play/thread/42114/
И с переходами по ссылкам к номерам страниц:
Да - http://test.tulius.com/play/thread/42154/?page=1 
Нет - http://test.tulius.com/play/thread/42146/?page=1
Не прослеживаю закономерности

**Comment by kozzztik** [comment]
Исправлено с PR #68
