### ISSUE TITLE
Проблемы с созданием тем с голосованием в вариации

### ISSUE THREAD

**Issue by milana-tulius** [kozzztik/tulius#89]
Проблема выявлена с суперадминского интерфейса.
Или возникает исключение.
http://test.tulius.co-de.org/play/add_thread/42224/#
Или ничего не происходит, и при этом отдельные поля подсвечиваются желтым или голубым цветом.

**Comment by milana-tulius** [comment]
![1](https://user-images.githubusercontent.com/31632369/80923784-5a6a2680-8d8e-11ea-821a-b7e424768942.png)

**Comment by kozzztik** [comment]
Проблема была из-за того, что для вариации не создался форум, и к ней прилинковался форум оригинальной вариации из которой она скопирована. Из-за этого побился форум. Саму проблему в БД я поправил, но вообще надо разобраться почему это случилось. Судя по всему в копировании вариации некорректно работает транзакция.

**Comment by milana-tulius** [comment]
Проблема была актуальна для старой версии форума
